#!/usr/bin/env bash
#Transfers file to given server 
#Check num of params
if [[ $# -ne 4 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 2
fi
#Copy file
        scp -i "$4" -o 'StrictHostKeyChecking=no' "$1" "$3@$2":~/
