#!/usr/bin/env bash
#Transfers file to given server 
case "$" in
    4)
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
        ;;
    *)
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        ;;
esac
