#!/usr/bin/env bash
#Installs nginx and sets up page
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /var/www/html
sudo sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /var/www/html;
    index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
service nginx restart
