#!/usr/bin/env bash
#Installs nginx and sets up page
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /var/www/html
sudo service nginx start
sudo sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

service nginx start
