#!/usr/bin/env bash
#Installs nginx and sets up page
apt-get updated && apt-get install nginx -y

#Sets the content of the root nginx pages
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

#checks if thre is redirect_me
GREP_RES=$(grep "redirect_me" /etc/nginx/sites-available/default)
    if [[ -z $GREP_RES ]]; then
    #declare input
    IN_STRING="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
    #Add line in file
    sed -i "48i $IN_STRING" /etc/nginx/sites-available/default
fi

#checks if there is error_page_404
GREP RES=$(grep "error_page 404" /etc/nginx/site-available/default)
if [[ -z $GREP_RES ]]; then
    IN_STRING='\\n\error_page 404 /404.html;'
    sed -i "42i $IN_STRING" /etc/nginx/sites-available/default
fi
service nginx start