#!/usr/bin/env bash
#fizzbuzz
for num in {1..100}
do
	if [ $((num%5)) -ne 0 -a $((num%3)) -ne 0 ]
	then
		echo $num
	else
		if [ $((num%3)) -eq 0 -a $((num%5)) -eq 0 ]
		then
			echo "FizzBuzz"
		elif [ $((num%3)) -eq 0 ]
		then
			echo "Fizz"
		elif [ $((num%5)) -eq 0 ]
		then
			echo "Buzz"
		fi
	fi
done
