#!/usr/bin/env bash
#Prints Holberton School with bad and good luck to stdout
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo bad luck
	elif [ $x -eq 8 ]
	then
		echo good luck
	else
		echo Holberton School
	fi
	let x++
done
